package your.app.components;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

// Generated by the WOLips Templateengine Plug-in at Dec 12, 2008 7:46:26 PM
public class AutoCompletionExample extends WOComponent {
    public AutoCompletionExample(WOContext context) {
        super(context);
    }
}