package your.app.components;

import com.webobjects.appserver.WOContext;

import er.extensions.components.ERXComponent;

// Generated by the WOLips Templateengine Plug-in at Nov 23, 2008 3:06:36 PM
public class PageWrapper extends ERXComponent {
	
    public PageWrapper(WOContext context) {
        super(context);
    }
    
}