package your.app.components;

import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSTimestamp;

import er.extensions.components.ERXComponent;

// Generated by the WOLips Templateengine Plug-in at Nov 23, 2008 3:03:21 PM
public class PeriodicUpdate extends ERXComponent {
	
	public NSTimestamp now = new NSTimestamp();
	
    public PeriodicUpdate(WOContext context) {
        super(context);
    }
    
	public void periodicUpdateAction() {
		now = new NSTimestamp();
	}
}