package your.app.components;

import com.webobjects.appserver.WOContext;

import er.extensions.components.ERXComponent;

// Generated by the WOLips Templateengine Plug-in at Nov 23, 2008 3:06:08 PM
public class RPCExample extends ERXComponent {
	
    public RPCExample(WOContext context) {
        super(context);
    }
    
}