package your.app.components;

import your.app.Application;

import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSArray;

import er.extensions.components.ERXComponent;

// Generated by the WOLips Templateengine Plug-in at Nov 23, 2008 3:04:25 PM
public class SubmitOnChange extends ERXComponent {
	
    public SubmitOnChange(WOContext context) {
        super(context);
    }
    
	private String selectedState;
	public String stateItem;
	public NSArray stateList = new NSArray(new String[] {
		"State 1",
		"State 2",
		"State 3"
	});
	
	private String selectedCounty;
	public String countyItem;
	public NSArray countyList() {
		if (selectedState == null) {
			return null;
		}
		
		return new NSArray(new String[] {
			selectedState + " - County 1",
			selectedState + " - County 2",
			selectedState + " - County 3"
		});
	}
	
	public String selectedStreet;
	public String streetItem;
	public NSArray streetList() {
		if (selectedState == null || selectedCounty == null) {
			return null;
		}
		
		return new NSArray(new String[] {
			selectedCounty + " - Street 1",
			selectedCounty + " - Street 2",
			selectedCounty + " - Street 3"
		});
	}

	public void setSelectedState(String selectedState) {
		this.selectedState = selectedState;
		selectedCounty = null;
		selectedStreet = null;
	}
	public String selectedState() {
		return selectedState;
	}

	public void setSelectedCounty(String selectedCounty) {
		this.selectedCounty = selectedCounty;
		selectedStreet = null;
	}
	public String selectedCounty() {
		return selectedCounty;
	}
	
	public void updateAction() {
		Application.log.info("update action called");
	}
}