package your.app.components;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

// Generated by the WOLips Templateengine Plug-in at Dec 12, 2008 12:08:28 AM
public class TreeExample extends WOComponent {
    public TreeExample(WOContext context) {
        super(context);
    }
}