package your.app.components;

import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSTimestamp;

import er.extensions.components.ERXComponent;

// Generated by the WOLips Templateengine Plug-in at Nov 23, 2008 3:02:28 PM
public class UpdateLink extends ERXComponent {
	
	public NSTimestamp now = new NSTimestamp();
	
    public UpdateLink(WOContext context) {
        super(context);
    }
    
	public void updateTimeAction() {
		now = new NSTimestamp();
	}
	
}