package your.app.components;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

// Generated by the WOLips Templateengine Plug-in at Dec 12, 2008 8:14:19 AM
public class ViewSourcePage extends WOComponent {
	
	public String title;
	public String htmlURL;
	public String wodURL;
	public String javaURL;
	public String gwtURL;
	
    public ViewSourcePage(WOContext context) {
        super(context);
    }
    
}