package your.app.components;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

import er.extensions.components.ERXComponent;

// Generated by the WOLips Templateengine Plug-in at Dec 12, 2008 8:09:10 AM
public class ViewSource extends ERXComponent {
	
	//public static final String srcDir = "http://code.google.com/p/wogwt/source/browse/trunk/WOGWTDemo/Sources/";
    //public static final String componentsDir = "http://code.google.com/p/wogwt/source/browse/trunk/WOGWTDemo/Components/";
    //public static final String gwtDir = "http://code.google.com/p/wogwt/source/browse/trunk/WOGWTDemo/Sources/your/app/gwt/";
    	
	public static final String srcDir = "http://wogwt.googlecode.com/svn/trunk/WOGWTDemo/Sources/";
    public static final String componentsDir = "http://wogwt.googlecode.com/svn/trunk/WOGWTDemo/Components/";
    public static final String gwtDir = srcDir + "your/app/gwt/";
    
    public ViewSource(WOContext context) {
        super(context);
    }
    
    public WOComponent viewSource() {
    	WOComponent rootParent = rootParent();

    	ViewSourcePage nextPage = pageWithName(ViewSourcePage.class);
    	
    	nextPage.title = rootParent.getClass().getSimpleName() + " Source";
    	nextPage.htmlURL = componentsDir + rootParent.getClass().getSimpleName() + ".wo/" + rootParent.getClass().getSimpleName() + ".html";
    	nextPage.wodURL = componentsDir + rootParent.getClass().getSimpleName() + ".wo/" + rootParent.getClass().getSimpleName() + ".wod";
    	nextPage.javaURL = srcDir + rootParent.getClass().getName().replace('.', '/') + ".java";
    	nextPage.gwtURL = gwtDir + rootParent.getClass().getSimpleName() + "Script.java";
    	
    	return nextPage;
    }
    
    public WOComponent rootParent() {
    	WOComponent result = this;
    	while (result.parent() != null) {
    		result = result.parent();
    	}
    	return result;
    }
}