package your.app.components;

import your.app.gwt.CompileTimeIDCheckingScript;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSTimestamp;

// Generated by the WOLips Templateengine Plug-in at Dec 11, 2008 11:21:45 PM
public class CompileTimeIDChecking extends WOComponent {
	
	public NSTimestamp now = new NSTimestamp();
	
    public CompileTimeIDChecking(WOContext context) {
        super(context);
    }
    
    public String containerID() {
    	return CompileTimeIDCheckingScript.CONTAINER_ID;
    }
    
    public String updateLinkID() {
    	return CompileTimeIDCheckingScript.UPDATE_LINK_ID;
    }
    
    public void updateAction() {
    	now = new NSTimestamp();
    }
}