package your.app.components;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

// Generated by the WOLips Templateengine Plug-in at Dec 12, 2008 10:00:55 PM
public class DialogExample extends WOComponent {
    public DialogExample(WOContext context) {
        super(context);
    }
}