package your.app.components;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

// Generated by the WOLips Templateengine Plug-in at Jan 13, 2009 12:58:03 PM
public class ImageBundleExample extends WOComponent {
    public ImageBundleExample(WOContext context) {
        super(context);
    }
}