package your.app.components;

import com.webobjects.appserver.WOContext;

import er.extensions.components.ERXComponent;

// Generated by the WOLips Templateengine Plug-in at Oct 3, 2008 10:05:13 PM
public class Page2 extends ERXComponent {
	
    public Page2(WOContext context) {
        super(context);
    }
    
}