package your.app.components;

import your.app.Application;
import your.app.gwt.RichTextExampleScript;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

// Generated by the WOLips Templateengine Plug-in at Dec 11, 2008 10:24:29 PM
public class RichTextExample extends WOComponent {
	
	public String statusString;
	
    public RichTextExample(WOContext context) {
        super(context);
    }
    
    public void getRichTextAction() {
    	String richHTML = (String) context().request().formValueForKey(RichTextExampleScript.RICH_TEXT_KEY);
    	Application.log.info(richHTML);
    	statusString = "Server received HTML: " + richHTML;
    }
    
    public String containerID() {
    	return RichTextExampleScript.CONTAINER_ID;
    }
    
    public String statusContainerID() {
    	return RichTextExampleScript.STATUS_CONTAINER_ID;
    }
}