package your.app.components;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

// Generated by the WOLips Templateengine Plug-in at Dec 11, 2008 8:32:40 PM
public class RoundedCorners extends WOComponent {
    public RoundedCorners(WOContext context) {
        super(context);
    }
}